minimumReleaseAge: 0

packages:
  - server
  - desktop

onlyBuiltDependencies:
  - esbuild
  - electron-winstaller
  - "@surrealdb/node"
  - "@parcel/watcher"
  - lmdb
  - msgpackr-extract

allowBuilds:
  '@parcel/watcher': true
  electron-winstaller: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
